### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by Luminighty** [Luminighty/jelloscript#4]
The goal of this issue is to create a working online multiplayer interface capable of sending inputs over the network using socket.io

**Todo:**
- [x] Set up a basic Node.JS server
- [x] Static class
   - [x] Create lobby
   - [x] Join Lobby
   - [x] onNewPlayer
      - [x] new NetworkController
- [x] Send inputs over network

**Optional:**
- [x] Send messages over network
 - [x] Typed messages with listeners
- [ ] Variable syncing (?)
